### ISSUE TITLE
use Interrupt uart

### ISSUE THREAD

**Issue by BlackQube** [christophjurczyk/ATmega64M1_avr_uart#1]
Hi,
is it possible to use your uart lib with rx interrupt? I'm new in AVR programming and don't understand the Interrupt section in the datasheet of my ATMega64M1.

**Comment by christophjurczyk** [comment]
Hey,
in general it should work. I already enabled the interrupts in the UART init ([link](https://github.com/christophjurczyk/ATmegaxxM1_avr_libraries/blob/2a90e8901119aeb5de7f868a57b440db77cf3842/source/uart.c#L41)). You have to adapted my code a little bit for interrupt routines. [Here](https://www.avrfreaks.net/forum/tut-soft-using-usart-interrupt-driven-serial-comms?page=all) is an example of using interrupts on other ATMega controllers. Take care that the registers have different names on the 64M1.
But I didn't tried it on the 64M1, as I didn't needed at that time.
